[commit]
allow_merge_commits = false
# Bypass checks for bot/automation authors and co-authors:
ignore_authors = ["dependabot[bot]", "renovate[bot]", "copilot[bot]"]

[branch]
# https://conventional-branch.github.io/
conventional_branch = true
allow_branch_names = [
  "^release-please--branches--.*$",
  "^dependabot/.*$",
  "^v[0-9]+\\.[0-9]+\\.[0-9]+$"
]
