---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: "chore"
    labels:
      - dependencies
    groups:
      deps-external:
        patterns:
          - '*'
    cooldown:
      default-days: 7
  - package-ecosystem: pre-commit
    directory: /
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: "chore"
    labels:
      - dependencies
    groups:
      deps-pre-commit:
        patterns:
          - '*'
    cooldown:
      default-days: 7

      ##### TODO need typescript here somewhere
