---
name: Code Checks
on:
  push:
    branches:
      - main
    tags:
      - v*.*.*
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, ready_for_review]
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      force_release:
        description: Force release
        required: false
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  prek-checks:
    name: Prek Checks
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
    steps:
      - name: "Cleaning up"
        uses: gacts/run-and-post-run@598d7a875d5620e0457490555b5e18e46082aa47 # v1.4.4
        with:
          run: |
            echo "Pre-Check Cleanup"
            echo "~/.local" | xargs rm -rf
          post: |
            echo "Post-Check Cleanup"
            echo "~/.local" | xargs rm -rf

      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up mise
        uses: jdx/mise-action@9e7f7633ff6f6d6048a9418a68d48f288f50eb14 # v4.2.3
        env:
          MISE_INSTALL_FROM_GITHUB: 1
        with:
          cache: false
          version: ${{ vars.MISE_VERSION }}

      - name: Run prek checks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: prek run --all-files --show-diff-on-failure

  build:
    name: Build TypeScript distribution
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    needs:
      - prek-checks
    steps:
      - name: "Cleaning up"
        uses: gacts/run-and-post-run@598d7a875d5620e0457490555b5e18e46082aa47 # v1.4.4
        with:
          run: |
            echo "Pre-Check Cleanup"
            echo "~/.local" | xargs rm -rf
          post: |
            echo "Post-Check Cleanup"
            echo "~/.local" | xargs rm -rf

      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up mise
        uses: jdx/mise-action@9e7f7633ff6f6d6048a9418a68d48f288f50eb14 # v4.2.3
        env:
          MISE_INSTALL_FROM_GITHUB: 1
        with:
          cache: false
          version: ${{ vars.MISE_VERSION }}

      - name: Build action bundle
        run: aube exec vite build

      - name: Store the distribution packages
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: startsWith(github.ref, 'refs/tags') || inputs.force_release == true
        with:
          name: action-distribution
          path: dist/
