name: Commit Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  commit-check:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:  # use permissions because use of pr-comments
      contents: read
      pull-requests: write
    steps:
      - name: "Cleaning up"
        uses: gacts/run-and-post-run@598d7a875d5620e0457490555b5e18e46082aa47 # v1.4.4
        with:
          run: |
            echo "Pre-Check Cleanup"
            echo "~/.local" | xargs rm -rf
          post: |
            echo "Post-Check Cleanup"
            echo "~/.local" | xargs rm -rf

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0  # Required for merge-base checks
          persist-credentials: false

      - uses: commit-check/commit-check-action@bbb6580f01838e475563514f115ec7ef41c9ddc7 # v2.11.1
        with:
          message: true
          branch: true
          author-name: true
          author-email: true
          job-summary: true
          pr-comments: ${{ github.event_name == 'pull_request' }}
