---
name: gh-action-pulse

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read

jobs:
  gh-action-pulse:
    name: gh-action-pulse
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      UV_LINK_MODE: copy
    permissions:
      contents: read
    steps:
      - name: "Cleaning up"
        uses: gacts/run-and-post-run@598d7a875d5620e0457490555b5e18e46082aa47 # v1.4.4
        with:
          run: |
            echo "Pre-Check Cleanup"
            echo "~/.local" | xargs rm -rf
          post: |
            echo "Post-Check Cleanup"
            echo "~/.local" | xargs rm -rf

      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up mise
        uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4.3.0
        env:
          MISE_INSTALL_FROM_GITHUB: 1
        with:
          cache: false
          version: ${{ vars.MISE_VERSION }}

      - name: Verify gh-action-pulse is applied
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_ACTION_PULSE_LOG_LEVEL: ${{ runner.debug == '1' && 'DEBUG' || 'INFO' }}
        run: |-
          # crazy-max/ghaction-github-labeler last tag is 150 days... so move up limit
          uv run --frozen --no-dev gh-action-pulse --max-age 200
          if ! git diff --quiet; then
            echo "::error::gh-action-pulse updates are not applied."
            echo "Run 'uv run gh-action-pulse' locally and commit the changes."
            git diff
            exit 1
          fi
